# Generated by Django 3.2.19 on 2024-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration_minutes', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
